# Generated by Django 3.0.5 on 2020-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
